class Station{
    Declare private attributes
     String name
    int longtitude
    int latitude
    Enum type

    declare constructer
    Station(attributes){
        this.attribute = attribute;
}
    default constructor(){
    }

    Declare getter and setters for:
        Name, longtitude, latitude, type
    set name(String name){
    get name()

    Set Long

    Create Methods
        Get user bus station
        Get location = return long and lat values.
        Add bus
        remove bus
        edit bus
    Create subclass
        Subclass bus station
        Subclass refuel station.
    
}
